package com.nn.json;

import com.nn.environment.MerchantCredentials;
import com.nn.environment.PaymentCredentials;

public class Payment {
	
	public static String transactionIntaition() {
		String request= "{\n"
		  		+ "	\"merchant\": {\n"
		  		+ "		\"signature\": \""+MerchantCredentials.signature+"\",\n"
		  		+ "		\"tariff\": \""+MerchantCredentials.tariff_id+"\"\n" 
		  		+ "	}, \n"
		  		+ "	\"customer\": {\n"
		  		+ "		\"gender\": \"m\", \n"
		  		+ "		\"first_name\": \"Norbert\",\n"
		  		+ "		\"last_name\": \"Maier\",\n"
		  		+ "		\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "        \"billing\": {\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "			\"house_no\": \"9\",\n"
		  		+ "			\"street\": \"Hauptstr\",\n"
		  		+ "			\"city\": \"Kaiserslautern\",\n"
		  		+ "			\"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "		\"customer_ip\": \"127.0.0.1\",\n"
		  		+ "		\"customer_no\": \"12345\",\n"
		  		+ "		\"birth_date\": \"1992-06-10\",\n"
		  		+ "        \"tel\": \"+49 089 123456\",\n"
		  		+ "        \"mobile\": \"+491747781423\",\n"
		  		+ "        \"fax\": \"+49 89 654321\",\n"
		  		+ "        \"shipping\": {\n"
		  		+ "			\"first_name\": \"Norbert\",\n"
		  		+ "			\"last_name\": \"Maier\",\n"
		  		+ "			\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "            \"house_no\": \"9\",\n"
		  		+ "            \"street\": \"Hauptstr\",\n"
		  		+ "            \"city\": \"Kaiserslautern\",\n"
		  		+ "            \"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"tel\": \"+49 089 123456\",\n"
		  		+ "            \"mobile\": \"+491747781423\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "       \"vat_id\":\"DE123456\",\n"
		  		+ "        \"tax_id\":\"123\",   \n"
		  		+ "        \"reg_no\":\"HRB1234\",   \n"
		  		+ "        \"session\":\"fedgrgst5653653hdgfsvgdsf622627e\"\n"
		  		+ "	},\n"
		  		+ "	\"transaction\": {\n"
		  		+ "        \"test_mode\": \""+MerchantCredentials.test_mode+"\",\n"
		  		+ "		\"payment_type\": \""+PaymentCredentials.sepa+"\",\n"
		  		+ "		\"amount\": \"100\",\n"
		  		+ "		\"currency\": \"EUR\",\n"
		  		+ "        \"order_no\": \"NOVALNET62160\",\n"
		  		+ "        \"hook_url\": \"https://developer.novalnet.de/demo/webhooks/\",\n"
		  		+ "		\"due_date\": \"2023-12-13\",\n"
		  		+ "		\"invoice_ref\": \"BNR-14-2132576\",\n"
		  		+ "        \"mandate_ref\":\"NN-12345678901234567\",\n"
		  		+ "        \"mandate_date\":\"2023-03-21\",\n"
		  		+ "        \"invoice_no\":\"852963\",\n"
		  		+ "        \"payment_data\": {\n"
		  		+ "            \"account_holder\": \"Max Mustermann\",\n"
		  		+ "            \"iban\": \""+PaymentCredentials.de_iban+"\",\n"
		  		+ "            \"bic\":\""+PaymentCredentials.de_bic+"\"\n"
		  		+ "        },\n"
		  		+ "        \"debit_reason_1\":\"www.test.com\"\n"
		  		+ "	},\n"
		  		+ "	\"custom\": {\n"
		  		+ "		\"lang\": \"EN\",\n"
		  		+ "        \"input1\":\"psp\",\n"
		  		+ "        \"inputval1\":\"novalnet\"\n"
		  		+ "	}\n"
		  		+ "}";
		return request;
		
	}

	
	public static String iban_bic(String iban, String bic) {
		String request= "{\n"
		  		+ "	\"merchant\": {\n"
		  		+ "		\"signature\": \""+MerchantCredentials.signature+"\",\n"
		  		+ "		\"tariff\": \""+MerchantCredentials.tariff_id+"\"\n" 
		  		+ "	}, \n"
		  		+ "	\"customer\": {\n"
		  		+ "		\"gender\": \"m\", \n"
		  		+ "		\"first_name\": \"Norbert\",\n"
		  		+ "		\"last_name\": \"Maier\",\n"
		  		+ "		\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "        \"billing\": {\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "			\"house_no\": \"9\",\n"
		  		+ "			\"street\": \"Hauptstr\",\n"
		  		+ "			\"city\": \"Kaiserslautern\",\n"
		  		+ "			\"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "		\"customer_ip\": \"127.0.0.1\",\n"
		  		+ "		\"customer_no\": \"12345\",\n"
		  		+ "		\"birth_date\": \"1992-06-10\",\n"
		  		+ "        \"tel\": \"+49 089 123456\",\n"
		  		+ "        \"mobile\": \"+491747781423\",\n"
		  		+ "        \"fax\": \"+49 89 654321\",\n"
		  		+ "        \"shipping\": {\n"
		  		+ "			\"first_name\": \"Norbert\",\n"
		  		+ "			\"last_name\": \"Maier\",\n"
		  		+ "			\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "            \"house_no\": \"9\",\n"
		  		+ "            \"street\": \"Hauptstr\",\n"
		  		+ "            \"city\": \"Kaiserslautern\",\n"
		  		+ "            \"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"tel\": \"+49 089 123456\",\n"
		  		+ "            \"mobile\": \"+491747781423\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "       \"vat_id\":\"DE123456\",\n"
		  		+ "        \"tax_id\":\"123\",   \n"
		  		+ "        \"reg_no\":\"HRB1234\",   \n"
		  		+ "        \"session\":\"fedgrgst5653653hdgfsvgdsf622627e\"\n"
		  		+ "	},\n"
		  		+ "	\"transaction\": {\n"
		  		+ "        \"test_mode\": \""+MerchantCredentials.test_mode+"\",\n"
		  		+ "		\"payment_type\": \""+PaymentCredentials.sepa+"\",\n"
		  		+ "		\"amount\": \"100\",\n"
		  		+ "		\"currency\": \"EUR\",\n"
		  		+ "        \"order_no\": \"NOVALNET62160\",\n"
		  		+ "        \"hook_url\": \"https://developer.novalnet.de/demo/webhooks/\",\n"
		  		+ "		\"due_date\": \"2023-12-13\",\n"
		  		+ "		\"invoice_ref\": \"BNR-14-2132576\",\n"
		  		+ "        \"mandate_ref\":\"NN-12345678901234567\",\n"
		  		+ "        \"mandate_date\":\"2023-03-21\",\n"
		  		+ "        \"invoice_no\":\"852963\",\n"
		  		+ "        \"payment_data\": {\n"
		  		+ "            \"account_holder\": \"Max Mustermann\",\n"
		  		+ "            \"iban\": \""+iban+"\",\n"
		  		+ "            \"bic\":\""+bic+"\"\n"
		  		+ "        },\n"
		  		+ "        \"debit_reason_1\":\"www.test.com\"\n"
		  		+ "	},\n"
		  		+ "	\"custom\": {\n"
		  		+ "		\"lang\": \"EN\",\n"
		  		+ "        \"input1\":\"psp\",\n"
		  		+ "        \"inputval1\":\"novalnet\"\n"
		  		+ "	}\n"
		  		+ "}";
		return request;
		
	}
	
	public static String no_nc(String email, String mobile, String no_nc) {
		String request1= "{\n"
		  		+ "	\"merchant\": {\n"
		  		+ "		\"signature\": \""+MerchantCredentials.signature+"\",\n"
		  		+ "		\"tariff\": \""+MerchantCredentials.tariff_id+"\"\n" 
		  		+ "	}, \n"
		  		+ "	\"customer\": {\n"
		  		+ "		\"email\": \""+email+"\",\n"
		  		+ "        \"mobile\": \""+mobile+"\",\n"
		  		+ "        \"no_nc\": \""+no_nc+"\",\n"
		  		+ "	},\n"
		  		+ "	\"transaction\": {\n"
		  		+ "        \"test_mode\": \""+MerchantCredentials.test_mode+"\",\n"
		  		+ "		\"payment_type\": \""+PaymentCredentials.sepa+"\",\n"
		  		+ "		\"amount\": \"100\",\n"
		  		+ "		\"currency\": \"EUR\",\n"
		  		+ "        \"order_no\": \"NOVALNET62160\",\n"
		  		+ "        \"hook_url\": \"https://developer.novalnet.de/demo/webhooks/\",\n"
		  		+ "		\"due_date\": \"2023-12-13\",\n"
		  		+ "		\"invoice_ref\": \"BNR-14-2132576\",\n"
		  		+ "        \"mandate_ref\":\"NN-12345678901234567\",\n"
		  		+ "        \"mandate_date\":\"2023-03-21\",\n"
		  		+ "        \"invoice_no\":\"852963\",\n"
		  		+ "        \"payment_data\": {\n"
		  		+ "            \"account_holder\": \"Max Mustermann\",\n"
		  		+ "            \"iban\": \"DE24300209002411761956\",\n"
		  		+ "            \"bic\":\"CMCIDEDDXXX\"\n"
		  		+ "        },\n"
		  		+ "        \"debit_reason_1\":\"www.test.com\"\n"
		  		+ "	},\n"
		  		+ "	\"custom\": {\n"
		  		+ "		\"lang\": \"EN\",\n"
		  		+ "        \"input1\":\"psp\",\n"
		  		+ "        \"inputval1\":\"novalnet\"\n"
		  		+ "	}\n"
		  		+ "}";
		return request1;
		
	}
	
	public static String name_acc_holder(String first_name, String last_name, String account_holder) {
		String request= "{\n"
		  		+ "	\"merchant\": {\n"
		  		+ "		\"signature\": \""+MerchantCredentials.signature+"\",\n"
		  		+ "		\"tariff\": \""+MerchantCredentials.tariff_id+"\"\n" 
		  		+ "	}, \n"
		  		+ "	\"customer\": {\n"
		  		+ "		\"gender\": \"m\", \n"
		  		+ "		\"first_name\": \""+first_name+"\",\n"
		  		+ "		\"last_name\": \""+last_name+"\",\n"
		  		+ "		\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "        \"billing\": {\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "			\"house_no\": \"9\",\n"
		  		+ "			\"street\": \"Hauptstr\",\n"
		  		+ "			\"city\": \"Kaiserslautern\",\n"
		  		+ "			\"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "		\"customer_ip\": \"127.0.0.1\",\n"
		  		+ "		\"customer_no\": \"12345\",\n"
		  		+ "		\"birth_date\": \"1992-06-10\",\n"
		  		+ "        \"tel\": \"+49 089 123456\",\n"
		  		+ "        \"mobile\": \"+491747781423\",\n"
		  		+ "        \"fax\": \"+49 89 654321\",\n"
		  		+ "        \"shipping\": {\n"
		  		+ "			\"first_name\": \"Norbert\",\n"
		  		+ "			\"last_name\": \"Maier\",\n"
		  		+ "			\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "            \"house_no\": \"9\",\n"
		  		+ "            \"street\": \"Hauptstr\",\n"
		  		+ "            \"city\": \"Kaiserslautern\",\n"
		  		+ "            \"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"tel\": \"+49 089 123456\",\n"
		  		+ "            \"mobile\": \"+491747781423\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "       \"vat_id\":\"DE123456\",\n"
		  		+ "        \"tax_id\":\"123\",   \n"
		  		+ "        \"reg_no\":\"HRB1234\",   \n"
		  		+ "        \"session\":\"fedgrgst5653653hdgfsvgdsf622627e\"\n"
		  		+ "	},\n"
		  		+ "	\"transaction\": {\n"
		  		+ "        \"test_mode\": \""+MerchantCredentials.test_mode+"\",\n"
		  		+ "		\"payment_type\": \""+PaymentCredentials.sepa+"\",\n"
		  		+ "		\"amount\": \"100\",\n"
		  		+ "		\"currency\": \"EUR\",\n"
		  		+ "        \"order_no\": \"NOVALNET62160\",\n"
		  		+ "        \"hook_url\": \"https://developer.novalnet.de/demo/webhooks/\",\n"
		  		+ "		\"due_date\": \"2023-12-13\",\n"
		  		+ "		\"invoice_ref\": \"BNR-14-2132576\",\n"
		  		+ "        \"mandate_ref\":\"NN-12345678901234567\",\n"
		  		+ "        \"mandate_date\":\"2023-03-21\",\n"
		  		+ "        \"invoice_no\":\"852963\",\n"
		  		+ "        \"payment_data\": {\n"
		  		+ "            \"account_holder\": \""+account_holder+"\",\n"
		  		+ "            \"iban\": \"DE24300209002411761956\",\n"
		  		+ "            \"bic\":\"CMCIDEDDXXX\"\n"
		  		+ "        },\n"
		  		+ "        \"debit_reason_1\":\"www.test.com\"\n"
		  		+ "	},\n"
		  		+ "	\"custom\": {\n"
		  		+ "		\"lang\": \"EN\",\n"
		  		+ "        \"input1\":\"psp\",\n"
		  		+ "        \"inputval1\":\"novalnet\"\n"
		  		+ "	}\n"
		  		+ "}";
		return request;
		
	}

	public static String amount_Currency_token(String amount, String currency, String createToken) {
		String request= "{\n"
		  		+ "	\"merchant\": {\n"
		  		+ "		\"signature\": \""+MerchantCredentials.signature+"\",\n"
		  		+ "		\"tariff\": \""+MerchantCredentials.tariff_id+"\"\n" 
		  		+ "	}, \n"
		  		+ "	\"customer\": {\n"
		  		+ "		\"gender\": \"m\", \n"
		  		+ "		\"first_name\": \"Norbert\",\n"
		  		+ "		\"last_name\": \"Maier\",\n"
		  		+ "		\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "        \"billing\": {\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "			\"house_no\": \"9\",\n"
		  		+ "			\"street\": \"Hauptstr\",\n"
		  		+ "			\"city\": \"Kaiserslautern\",\n"
		  		+ "			\"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "		\"customer_ip\": \"127.0.0.1\",\n"
		  		+ "		\"customer_no\": \"12345\",\n"
		  		+ "		\"birth_date\": \"1992-06-10\",\n"
		  		+ "        \"tel\": \"+49 089 123456\",\n"
		  		+ "        \"mobile\": \"+491747781423\",\n"
		  		+ "        \"fax\": \"+49 89 654321\",\n"
		  		+ "        \"shipping\": {\n"
		  		+ "			\"first_name\": \"Norbert\",\n"
		  		+ "			\"last_name\": \"Maier\",\n"
		  		+ "			\"email\": \"alexandersjones10@gmail.com\",\n"
		  		+ "			\"company\": \"A.B.C. Gerüstbau GmbH\",\n"
		  		+ "            \"house_no\": \"9\",\n"
		  		+ "            \"street\": \"Hauptstr\",\n"
		  		+ "            \"city\": \"Kaiserslautern\",\n"
		  		+ "            \"zip\": \"66862\",\n"
		  		+ "            \"country_code\": \"DE\",\n"
		  		+ "            \"tel\": \"+49 089 123456\",\n"
		  		+ "            \"mobile\": \"+491747781423\",\n"
		  		+ "            \"state\": \"Berlin\"\n"
		  		+ "		},\n"
		  		+ "       \"vat_id\":\"DE123456\",\n"
		  		+ "        \"tax_id\":\"123\",   \n"
		  		+ "        \"reg_no\":\"HRB1234\",   \n"
		  		+ "        \"session\":\"fedgrgst5653653hdgfsvgdsf622627e\"\n"
		  		+ "	},\n"
		  		+ "	\"transaction\": {\n"
		  		+ "        \"test_mode\": \""+MerchantCredentials.test_mode+"\",\n"
		  		+ "		\"payment_type\": \""+PaymentCredentials.sepa+"\",\n"
		  		+ "		\"amount\": \""+amount+"\",\n"
		  		+ "		\"currency\": \""+currency+"\",\n"
		  		+ "        \"order_no\": \"NOVALNET62160\",\n"
		  		+ "        \"hook_url\": \"https://developer.novalnet.de/demo/webhooks/\",\n"
		  		+ "		\"due_date\": \"2023-12-13\",\n"
		  		+ "		\"invoice_ref\": \"BNR-14-2132576\",\n"
		  		+ "        \"mandate_ref\":\"NN-12345678901234567\",\n"
		  		+ "        \"mandate_date\":\"2023-03-21\",\n"
		  		+ "        \"invoice_no\":\"852963\",\n"
		  		+ "        \"create_token\":\""+createToken+"\",\n"		  		
		  		+ "        \"payment_data\": {\n"
		  		+ "            \"account_holder\": \"Max Mustermann\",\n"
		  		+ "            \"iban\": \"DE24300209002411761956\",\n"
		  		+ "            \"bic\":\"CMCIDEDDXXX\"\n"
		  		+ "        },\n"
		  		+ "        \"debit_reason_1\":\"www.test.com\"\n"
		  		+ "	},\n"
		  		+ "	\"custom\": {\n"
		  		+ "		\"lang\": \"EN\",\n"
		  		+ "        \"input1\":\"psp\",\n"
		  		+ "        \"inputval1\":\"novalnet\"\n"
		  		+ "	}\n"
		  		+ "}";
		return request;
		
	}



}
